#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=10

start()
{
        [ -f /SDC/wps ] && {
                #cat /SDC/wps >> /etc/rc.button/wps
		cp /SDC/wps /etc/rc.button/wps
                rm /SDC/wps
        }
}
